### ISSUE TITLE
Retro

### ISSUE THREAD

**Issue by dyshay** [Mrpotatosse/AivyCore#3]
Salut,

J'aime bien ton projet par contre une portabilité  retro est possible ?

**Comment by Mrpotatosse** [comment]
j'ai ajouter une partie pour Dofus Retro , pour l'instant il n'y a aucun traitement des messages retro ( car je ne connais pas le protocol , ni comment le trouver x) ) , mais si jamais tu as envie de le faire c'est dans https://github.com/Mrpotatosse/AivyCore/blob/master/AivyDofus/Proxy/Callbacks/DofusRetroProxyClientReceiveCallback.cs dans OnReceive

**Comment by Dyshay** [comment]
Le proxy fait un truc vachement bizarre double voir triple redirection, je connais le protocol retro sur le bouts des doigts

**Comment by Mrpotatosse** [comment]
Le client DofusRetro essaye de se connecter à un serveur local ( qu'il crée surrement je ne sais pas trop ) , j'ai un peu modifié le SocketHook pour qu'il ne redirige pas les IP local

**Comment by Dyshay** [comment]
C'est opérationnel, je te remercie en tous cas pour ton boulot, j'avais un mitm basique mais le SocketHook je le gére pas trop

**Comment by Dyshay** [comment]
Si jamais tu as besoin de discuté protocol rétro n’hésite pas Dyshay#1010

**Comment by Mrpotatosse** [comment]
Je ne dev pas du Dofus retro malheuresement ^^ ( c'est juste à cause du graphisme que je trouve insupportable ) mais si jamais je me penche un peu plus en détail dessus , je te contacterai.

**Comment by Dyshay** [comment]
En tous cas merci

**Comment by Dyshay** [comment]
Possible d'avoir ton discord ?

**Comment by Mrpotatosse** [comment]
MrPot#2029

**Comment by FoxStyle-dofus** [comment]
Salut les gars, vous allez bien?

Je suis programmer .NET (WebApp) depuis quelques années déjà et de métier également. Le bottage Dofus m'intéresse vu que je veux en apprendre d'avantage dans ce domaine.
Je suis tombé sur le projet de Dyshay hier soir et j'ai un peu chipoté sans arriver à faire grand chose, ce qui m'a amené à ton projet MrPotatosse, lequel je déchiffre ce matin.
J'aimerais en apprendre d'avantage sur vos solutions, j'ai déjà ajouter le discord de MrPot mais le tiens Dyshay ne semble pas fonctionner.
Si ça vous tente une collab ou juste répondre à quelques questions, ce serait génial!

Une bonne journée!
